# -*- coding: utf-8 -*-
"""bayesian.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17CP8a-6NKH7R9qC87HomHq8KNjLd72u_
"""

import orbit
from orbit.utils.dataset import load_iclaims
from orbit.models.dlt import DLTFull
from orbit.diagnostics.plot import plot_predicted_data


# LOAD PRE-EXISTING DATASET.
# MODIFY HERE TO LOAD OUR DATASET
df = load_iclaims()

# DATA COLUMN IS THE TIME RELATED COLUMN. IN OUR CASE, THIS SHOULD BE WEEK
date_col = 'week'

# REG_COL IS THE REGRESSION COLUMNS WE ARE LOOKING AT
reg_col = ['sp500','vix','claims','trend.filling']

# RESPONSE COL IS THE OUTPUT WE NEED
response_col = 'trend.job'
# print(df.dtypes)

# PARTITIONING
test_size = 52
train_df = df[:-test_size]
test_df = df[-test_size:]

# CREATE DAMPED LOCAL TIME MODEL
dts = DLTFull(
    response_col=response_col,
    date_col=date_col,
    seasonality=52,
    seed=8888,
    regressor_col=reg_col
)


dts.fit(df=train_df)
predicted_df = dts.predict(df=test_df)
_ = plot_predicted_data(train_df, predicted_df, date_col, response_col, title='Prediction with DLT')